version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb_data:/data/db
    networks:
      - filmi-leidja-network
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always

  filmi-leidja:
    image: oskarunn/filmi-leidja:latest
    container_name: filmi-leidja
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - filmi-leidja-network
    ports:
      - "8080:8080"

volumes:
  mongodb_data:
    driver: local
    name: mongodb_data

networks:
  filmi-leidja-network: